name: Tests

on: [push, pull_request]

env:
  ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/21.4.7075529

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v2

      - name: Update bdk-ffi git submodule
        run: |
          git submodule set-url bdk-ffi https://github.com/bitcoindevkit/bdk-ffi.git
          git submodule update --init bdk-ffi

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            bdk-ffi/target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Install rust android targets
        run: rustup target add x86_64-linux-android aarch64-linux-android armv7-linux-androideabi

      - name: Build bdk-android library
        run: ./gradlew :android:buildAndroidLib

      - name: Run Android tests
        run: ./gradlew :android:test --console=rich

      - name: Build bdk-jvm library
        run: ./gradlew :jvm:buildJvmLib

      - name: Run JVM tests
        run: ./gradlew :jvm:test --console=rich
